import tkinter as tk
main=tk.Tk()
main.title("TEST")
bg = tk.PhotoImage( file = "wallpaper.png") 
label1 = tk.Label(main,image = bg) 
label1.place(x = 0,y =0) 
main.geometry("1080x1910")
b=tk.Button(main,text="SHUT",width=25,activebackground="blue", activeforeground="white")
b.pack()
label = tk.Label(main, text="Hello, Tkinter!", bg="red", fg="teal")
label.pack()
entry = tk.Entry(main, selectbackground="red", selectforeground="black")
entry.pack()
main.mainloop()